import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { after, test } from "node:test";
import { and, eq, inArray, sql } from "drizzle-orm";
import {
  campaigns,
  closeDb,
  contacts,
  discoveryCandidates,
  drafts,
  generateDraftCommand,
  getDb,
  jobs,
  maybeAutoGenerateDraft,
  organizations,
  researchFacts,
  researchSnapshots
} from "../src";

// T-026BI — auto-generate one cold draft when an org is draft-ready:
// published snapshot + active facts + an addressable contact + active
// campaign + no existing draft + open-review cap not exhausted. The helper is
// driven directly with seeded rows; success = a job.generate_cold_draft was
// enqueued for the org. Each negative removes exactly one precondition.

const PREFIX = "auto-draft-";

after(async () => {
  await closeDb();
});

type Seed = {
  campaignId: string;
  organizationId: string;
  snapshotId: string;
};

async function seed(
  suffix: string,
  opts: {
    campaignStatus?: string;
    snapshotStatus?: string;
    withFacts?: boolean;
    withEmail?: boolean;
    maxOpenDraftReviews?: number;
  } = {}
): Promise<Seed> {
  const db = getDb();
  const [campaign] = await db
    .insert(campaigns)
    .values({
      name: `${PREFIX}camp-${suffix}`,
      objective: "test",
      status: opts.campaignStatus ?? "active",
      maxOpenDraftReviews: opts.maxOpenDraftReviews ?? 25
    })
    .returning({ id: campaigns.id });
  assert.ok(campaign);

  const [org] = await db
    .insert(organizations)
    .values({ name: `${PREFIX}org-${suffix}`, domain: `${PREFIX}${suffix}.example` })
    .returning({ id: organizations.id });
  assert.ok(org);

  await db.insert(discoveryCandidates).values({
    campaignId: campaign.id,
    proposedName: `${PREFIX}org-${suffix}`,
    domain: `${PREFIX}${suffix}.example`,
    status: "enriched",
    matchedOrganizationId: org.id
  });

  const [snapshot] = await db
    .insert(researchSnapshots)
    .values({
      organizationId: org.id,
      snapshotVersion: 1,
      status: opts.snapshotStatus ?? "published"
    })
    .returning({ id: researchSnapshots.id });
  assert.ok(snapshot);

  if (opts.withFacts !== false) {
    await db.insert(researchFacts).values({
      snapshotId: snapshot.id,
      factText: "Operates a public product.",
      status: "active",
      confidence: 80,
      safeForCopy: true
    });
  }

  if (opts.withEmail !== false) {
    await db.insert(contacts).values({
      organizationId: org.id,
      email: `${PREFIX}lead-${suffix}@example.com`,
      fullName: "Auto Lead"
    });
  }

  return { campaignId: campaign.id, organizationId: org.id, snapshotId: snapshot.id };
}

async function draftJobs(orgId: string) {
  const db = getDb();
  return db
    .select({ id: jobs.id })
    .from(jobs)
    .where(and(
      eq(jobs.jobType, "job.generate_cold_draft"),
      eq(jobs.targetEntityId, orgId)
    ));
}

test("draft-ready org auto-generates one cold draft", async (t) => {
  const suffix = randomUUID();
  await clearArtifacts();
  t.after(clearArtifacts);

  const s = await seed(suffix);
  await maybeAutoGenerateDraft({ organizationId: s.organizationId });

  assert.equal((await draftJobs(s.organizationId)).length, 1, "one draft job enqueued");
});

test("does not duplicate when a draft already exists", async (t) => {
  const suffix = randomUUID();
  await clearArtifacts();
  t.after(clearArtifacts);

  const s = await seed(suffix);
  await maybeAutoGenerateDraft({ organizationId: s.organizationId });
  await maybeAutoGenerateDraft({ organizationId: s.organizationId });

  // generate_draft's own concurrencyKey + the no-existing-draft check both
  // guard; either way exactly one job.
  assert.equal((await draftJobs(s.organizationId)).length, 1, "still one job");
});

test("does not generate when snapshot is not published", async (t) => {
  const suffix = randomUUID();
  await clearArtifacts();
  t.after(clearArtifacts);

  const s = await seed(suffix, { snapshotStatus: "draft" });
  await maybeAutoGenerateDraft({ organizationId: s.organizationId });

  assert.equal((await draftJobs(s.organizationId)).length, 0, "no job — unverified snapshot");
});

test("does not generate without an addressable contact", async (t) => {
  const suffix = randomUUID();
  await clearArtifacts();
  t.after(clearArtifacts);

  const s = await seed(suffix, { withEmail: false });
  await maybeAutoGenerateDraft({ organizationId: s.organizationId });

  assert.equal((await draftJobs(s.organizationId)).length, 0, "no job — no email contact");
});

test("does not generate without active facts", async (t) => {
  const suffix = randomUUID();
  await clearArtifacts();
  t.after(clearArtifacts);

  const s = await seed(suffix, { withFacts: false });
  await maybeAutoGenerateDraft({ organizationId: s.organizationId });

  assert.equal((await draftJobs(s.organizationId)).length, 0, "no job — no active facts");
});

test("does not generate when the campaign is not active", async (t) => {
  const suffix = randomUUID();
  await clearArtifacts();
  t.after(clearArtifacts);

  const s = await seed(suffix, { campaignStatus: "paused" });
  await maybeAutoGenerateDraft({ organizationId: s.organizationId });

  assert.equal((await draftJobs(s.organizationId)).length, 0, "no job — campaign not active");
});

test("does not generate when the open-draft-review cap is reached", async (t) => {
  const suffix = randomUUID();
  await clearArtifacts();
  t.after(clearArtifacts);

  // cap 0 → any open review (here zero, but cap 0 means never) blocks.
  const s = await seed(suffix, { maxOpenDraftReviews: 0 });
  await maybeAutoGenerateDraft({ organizationId: s.organizationId });

  assert.equal((await draftJobs(s.organizationId)).length, 0, "no job — review cap reached");
});

test("generate_draft with replaceExisting discards the org's current draft", async (t) => {
  const suffix = randomUUID();
  await clearArtifacts();
  t.after(clearArtifacts);

  const s = await seed(suffix);
  const db = getDb();
  // Seed an existing open draft for the org's addressable contact.
  const [contact] = await db
    .select({ id: contacts.id })
    .from(contacts)
    .where(eq(contacts.organizationId, s.organizationId))
    .limit(1);
  assert.ok(contact);
  const [oldDraft] = await db
    .insert(drafts)
    .values({
      contactId: contact.id,
      campaignId: s.campaignId,
      subject: "Old subject",
      body: "Old body",
      status: "draft"
    })
    .returning({ id: drafts.id });
  assert.ok(oldDraft);

  const result = await generateDraftCommand({
    source: "operator",
    payload: {
      organizationId: s.organizationId,
      operatorBrief: "Regenerate from scratch",
      campaignId: s.campaignId,
      replaceExisting: true
    }
  });
  assert.equal(result.ok, true);

  // Old draft is now discarded; the new generate_cold_draft job is enqueued.
  const [oldRow] = await db
    .select({ status: drafts.status })
    .from(drafts)
    .where(eq(drafts.id, oldDraft.id))
    .limit(1);
  assert.equal(oldRow?.status, "discarded", "old draft discarded by replaceExisting");
  assert.equal((await draftJobs(s.organizationId)).length, 1, "new draft job enqueued");
});

async function clearArtifacts(): Promise<void> {
  const db = getDb();
  const orgRows = await db
    .select({ id: organizations.id })
    .from(organizations)
    .where(sql`${organizations.name} like '${sql.raw(PREFIX)}%'`);
  const orgIds = orgRows.map((r) => r.id);
  if (orgIds.length === 0) return;

  // draft jobs target the org directly; draft rows + commands link via contact.
  const draftRows = await db
    .select({ id: drafts.id })
    .from(drafts)
    .innerJoin(contacts, eq(contacts.id, drafts.contactId))
    .where(inArray(contacts.organizationId, orgIds));
  const draftIds = draftRows.map((r) => r.id);
  if (draftIds.length > 0) {
    await db.delete(drafts).where(inArray(drafts.id, draftIds));
  }
  // event_log.job_id -> jobs; clear events for our jobs before the jobs.
  const jobRows = await db
    .select({ id: jobs.id })
    .from(jobs)
    .where(inArray(jobs.targetEntityId, orgIds));
  const jobIds = jobRows.map((r) => r.id);
  if (jobIds.length > 0) {
    await db.execute(sql`delete from event_log where job_id in (
      select id from jobs where target_entity_id in (
        select id from organizations where name like '${sql.raw(PREFIX)}%'
      )
    )`);
    await db.delete(jobs).where(inArray(jobs.id, jobIds));
  }
  const snapRows = await db
    .select({ id: researchSnapshots.id })
    .from(researchSnapshots)
    .where(inArray(researchSnapshots.organizationId, orgIds));
  const snapIds = snapRows.map((r) => r.id);
  if (snapIds.length > 0) {
    await db.delete(researchFacts).where(inArray(researchFacts.snapshotId, snapIds));
    await db.delete(researchSnapshots).where(inArray(researchSnapshots.id, snapIds));
  }
  await db.delete(contacts).where(inArray(contacts.organizationId, orgIds));
  await db.delete(discoveryCandidates).where(inArray(discoveryCandidates.matchedOrganizationId, orgIds));
  // event_log + commands reference the org as entity/target.
  await db.execute(sql`delete from event_log where entity_id in (
    select id from organizations where name like '${sql.raw(PREFIX)}%'
  )`);
  await db.execute(sql`delete from commands where target_entity_id in (
    select id from organizations where name like '${sql.raw(PREFIX)}%'
  )`);
  await db.delete(organizations).where(inArray(organizations.id, orgIds));
  await db.execute(sql`delete from campaigns where name like '${sql.raw(PREFIX)}%'`);
}
